# Generated by Django 5.0.4 on 2024-05-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_alter_info_borrow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='borrow',
            field=models.DateTimeField(blank=True, default=0, verbose_name='Borrowed on'),
        ),
    ]
