# Generated by Django 5.0.4 on 2024-05-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0007_alter_info_borrow_alter_info_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='borrow',
            field=models.DateField(verbose_name='Borrowed on'),
        ),
    ]
