# Generated by Django 5.0.4 on 2024-06-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0008_alter_info_borrow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='borrow',
            field=models.DateTimeField(verbose_name='Borrowed on'),
        ),
        migrations.AlterField(
            model_name='info',
            name='deadline',
            field=models.DateTimeField(verbose_name='Return Before'),
        ),
    ]
