# Generated by Django 5.0.4 on 2024-06-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0009_alter_info_borrow_alter_info_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='borrow',
            field=models.DateField(verbose_name='Borrowed on'),
        ),
        migrations.AlterField(
            model_name='info',
            name='deadline',
            field=models.DateField(verbose_name='Return Before'),
        ),
    ]
