# Generated by Django 5.0.4 on 2024-06-24 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0011_alter_info_borrow_alter_info_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='item',
            field=models.CharField(choices=[('green', 'GREEN'), ('blue', 'BLUE'), ('red', 'RED'), ('orange', 'ORANGE'), ('black', 'BLACK')], max_length=100, verbose_name='Item Name'),
        ),
    ]
