# Generated by Django 5.0.4 on 2024-06-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0012_alter_info_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='status',
            field=models.CharField(blank=True, choices=[('True', 'On Time'), ('False', 'Past Deadline')], max_length=20, verbose_name='Current Status'),
        ),
        migrations.AlterField(
            model_name='info',
            name='item',
            field=models.CharField(max_length=100, verbose_name='Item Name'),
        ),
    ]
