# Generated by Django 5.0.4 on 2025-05-06 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0014_item_alter_info_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.item'),
        ),
    ]
