# Generated by Django 5.0.4 on 2025-05-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0020_auto_20250506_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='item',
            field=models.CharField(max_length=100, verbose_name='Item Name'),
        ),
    ]
