# Generated by Django 5.0.4 on 2025-05-06 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0021_alter_info_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_page.item'),
        ),
    ]
